server:
  port: @server.port@

spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
  flyway:
    schemas: midgard

clearing-service:
  package-size: 25
  inner-package-size: 500
  revision: 60000
  retries-hour-count: 23
  scheduler-pool-size: 5
  error-timeout: 1000
#  adapters:
#    - name: mock
#      url: http://localhost:8023/v1/adapter/mock
#      networkTimeout: 120000
#      providerId: 1
#    - name: test
#      url: http://localhost:8023/v1/adapter/test
#      networkTimeout: 120000
#      providerId: 2

  invoicing:
    url: http://localhost:8023/v1/invoicing
    networkTimeout: 30000

kafka:
  bootstrap-servers: localhost:19092
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 5
    client-id: midgard
    group-id: "MidgardListener"
    enable-auto-commit: false
    auto-offset-reset: latest
    max-poll-records: 20
    connections-max-idle-ms: 300000
    session-timeout-ms: 300000
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false
  retry-policy:
    maxAttempts: 10

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy