server:
  port: @server.port@

spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
  flyway:
    schemas: midgard, feed

clearing-service:
  package-size: 25
  inner-package-size: 500
  revision: 60000
  retries-hour-count: 23
  scheduler-pool-size: 5
  adapters:
    mts:
      name: MTS
      url: http://localhost:8023/v1/clearing/mts
      networkTimeout: 120000
      providerId: 115
  invoicing:
    url: http://invoicing:8023/v1/invoicing
    networkTimeout: 120000
  schedule:
    mts: "00 01 00 * * *"

import:
  trx-pool-size: 30
  migration:
    delay: 30000
  init-last-event-id: 205612089

retry-policy:
  maxAttempts: 10

bm:
  pollingEnabled: false
  invoicing:
    url: http://bustermaze:8022/repo
    workersCount: 5
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300
  partyManagement:
    url: http://bustermaze:8022/repo
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300

kafka:
  bootstrap-servers: localhost:19092
  client-id: midgard
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 5
    group-id: "MidgardListener"
    enable-auto-commit: false
    auto-offset-reset: latest
    max-poll-records: 20
    conn-max-idle-ms: 300000
    session-timeout-ms: 300000
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy