server:
  port: @server.port@

spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
  flyway:
    schemas: midgard, feed

clearing-service:
  package-size: 25
  revision: 60000
  adapters:
    mts:
      name: MTS
      url: http://clearing:8023/v1/clearing/mts
      networkTimeout: 5000
      providerId: 115
  schedule:
    mts: "00 30 00 * * *"

import:
  trx-pool-size: 30
  migration:
    delay: 30000
  init-last-event-id: 205612089

retry-policy:
  maxAttempts: 10

bm:
  pollingEnabled: true
  partyManagement:
    url: http://bustermaze:8022/repo
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300

dmt:
  url: http://dominant:8022/v1/domain/repository
  networkTimeout: 5000
  polling:
    delay: 3000
    maxQuerySize: 10

invoicing:
  kafka.topic: mg-invoice-100-2

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  #    ssl:
  #      trust-store-location: "classpath:cert/truststore.p12"
  #      trust-store-password: "kenny12"
  #      key-store-location: "classpath:cert/kenny-k.struzhkin.p12"
  #      key-store-password: "kenny"
  #      key-password: "kenny"
  #      key-store-type: PKCS12
  #      trust-store-type: PKCS12
  consumer:
    group-id: "TestListener"
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: com.rbkmoney.newway.serde.SinkEventDeserializer
    enable-auto-commit: false
    auto-offset-reset: earliest
    client-id: test
  listener:
    type: batch
    ack-mode: manual
    concurrency: 1
    poll-timeout: 1000 #ms
    no-poll-threshold: 5.0 # * poll-timeout value = when consumer is dead
    log-container-config: true
    monitor-interval: 10s
  client-id: test
  properties:
    security:
      protocol: PLAINTEXT

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy