server:
  port: @server.port@

spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: midgard, feed

clearing-service:
  package-size: 30
  revision: 30000
  adapters:
    mts:
      name: mts
      url: http://clearing:8023/v1/clearing/mts
      networkTimeout: 5000
      providerId: 1
    test:
      name: test
      url: http://clearing:8023/v1/clearing/test
      networkTimeout: 5000
      providerId: 101

import:
  trx-pool-size: 100
  migration:
    delay: 10000

retry-policy:
  maxAttempts: 10

bm:
  pollingEnabled: true
  invoicing:
    url: http://bustermaze:8022/repo
    workersCount: 5
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300
  partyManagement:
    url: http://bustermaze:8022/repo
    polling:
      delay: 10000
      retryDelay: 1000
      maxPoolSize: 1
      maxQuerySize: 300

dmt:
  url: http://dominant:8022/v1/domain/repository
  networkTimeout: 5000
  polling:
    delay: 3000
    maxQuerySize: 10

management.metrics.export.statsd.flavor: etsy